### PR TITLE
Enable CI builds

### PR DESCRIPTION
**Pull request by kryksyh**
@saintmatthieu let me know if you want to add anything besides the plugin, or change names\strings

### CODE REVIEW

**Comment by kryksyh** [comment]
@saintmatthieu actions in action: https://github.com/kryksyh/loop-tempo-estimator/actions/runs/11764222400

**Comment by saintmatthieu** [comment]
> @saintmatthieu let me know if you want to add anything besides the plugin, or change names\strings

@kryksyh yes: loop-tempo-estimator-vamp.cat should also be part of the artifacts. When copied in the vamp directory together with the DLL,  it allows hosts to organize the plugin in the correct category:
image

**Comment by saintmatthieu** [comment]
Related: on https://www.vamp-plugins.org/download.html, one can find plugins, and it says
> This page lists plugins made by research groups and developers around the world. It is generated automatically from [RDF descriptions](https://www.vamp-plugins.org/rdf/plugins) published by the plugin authors.

Haven't figured out how to do this.

**Comment by saintmatthieu** [comment]
Resolves: https://github.com/saintmatthieu/loop-tempo-estimator/issues/3

**Comment by kryksyh** [comment]
@saintmatthieu I couldn't find documentation on the format for those files (what is `plugbase` is a mystery to me). It's up to you to check and update the content. 
- `cat` file is based on one of the examples.
- `rdf` is generated with `vamp-rdf-template-generator -i libloop-tempo-estimator-vamp`

CI script is sub-optimal, and the project need to be refactored to use CPack instead of manually copying files here and there. But I couldn't fix conflicts with `vamp-sdk`, so lets keep it for later.

**Comment by saintmatthieu** [comment]
I'm perfectly fine with the "manual" copying. I have zero experience with CPack, but if you think it's better then I'm open.
Thanks again !

**Pull request merged**
